AOM_MAPPING = {
    "N° SIREN AOM": "N_SIREN_AOM",
    "Groupements 2023": "Nom de l'AOM",
    "Bassin de mobilité (1 champ)": "Bassin_de_mobilite",
    "Lien base BANATIC": "Lien_Banatic",
    "Id réseau": "Id_reseau",
    "Nom du réseau": "Nom_reseau",
    "Forme juridique": "Forme_juridique_De_l_AOM",
    "Commune principale": "Commune_principale_De_l_AOM",
    "N°SIREN Commune principale": "N_SIREN_Commune_principale",
    "Région": "Region",
    "Département": "Departement",
    "Nom du Président": "Nom_du_President",
    "Adresse du siège": "Adresse_du_siege_De_l_AOM",
    "Adresse mail": "Adresse_mail",
    "Nombre de membres": "Nombre_de_membre_De_l_AOM",
    "Nombre de communes du RT": "Nombre_de_commune_De_l_AOM",
    "Population totale 2019 (Banatic)": "Population_De_l_AOM",
    "Surface (km²)": "Surface_km2_",
}


COMMUNES_MAPPING = {
    "Id réseau": "Id_reseau",
    "Nom du réseau": "Nom_du_reseau",
    "N° SIREN AOM": "N_SIREN_AOM",
    "Nom de l'AOM": "Nom_de_l_AOM",
    "Forme juridique de l'AOM": "Forme_juridique_De_l_AOM",
    "N° SIREN groupement": "N_SIREN_Groupement",
    "Bassin de mobilité 1": "Bassin_de_mobilite_1",
    "Bassin de mobilité 2": "Bassin_de_mobilite_2",
    "Bassin de mobilité 3": "Bassin_de_mobilite_3",
    "Région siège": "Region_siege",
    "Département siège": "Departement_siege",
    "N° SIREN groupement": "N_SIREN_Groupement",
    "Lien Banatic": "Lien_Banatic",
    "Nom du groupement": "Nom_du_groupement",
    "Nature juridique du groupement": "Nature_juridique_Du_groupement",
    "Nombre de membres": "Nombre_De_membres",
    "Population totale 2019 (Banatic)": "Population_totale_2019_Banatic_",
    "Siren membre": "Siren_membre",
    "N° INSEE": "N_INSEE",
    "Nom membre": "Nom_membre",
    "Surface (km²)": "Surface_km2_",
    "intitulé commune wikipédia": "intitule_commune_wikipedia",
    "Lien Page wikipedia": "Lien_Page_wikipedia",
}
