TAG_DP_MAPPING = {
    "accompagnant PMR": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "accompagnateur": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "adulte salarié": {"tag": None, "fournisseur": "FRANCE TRAVAIL"},
    "allocataire": {"tag": "Quotient Familial", "fournisseur": "CNAF / MSA"},
    "Allocation Adulte Handicapé": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "Allocation Compensatrice Tierce Personne": {
        "tag": None,
        "fournisseur": None,
    },
    "Allocation Personnalisée Autonomie": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "allocation RSA activité": {"tag": "RSA", "fournisseur": "CNAF / MSA"},
    "Allocation Solidarité Spécifique": {"tag": None, "fournisseur": None},
    "Allocation Soutien Familial": {"tag": None, "fournisseur": None},
    "allocation vieillesse": {"tag": None, "fournisseur": None},
    "allocations journalières": {"tag": None, "fournisseur": None},
    "ancien combattant": {"tag": None, "fournisseur": None},
    "apprenti": {"tag": "Statut étudiant", "fournisseur": "CNOUS"},
    "asile": {"tag": None, "fournisseur": None},
    "autonome fiscalement": {"tag": None, "fournisseur": None},
    "autonome marche": {"tag": None, "fournisseur": None},
    "avenir Jeunes": {"tag": None, "fournisseur": None},
    "aveugle": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "ayant-droit": {"tag": None, "fournisseur": None},
    "baccalauréat": {"tag": "Statut élève", "fournisseur": None},
    "barre bleue": {"tag": None, "fournisseur": None},
    "barre rouge": {"tag": None, "fournisseur": None},
    "barres bleues": {"tag": None, "fournisseur": None},
    "barres rouges": {"tag": None, "fournisseur": None},
    "bénéficiaire": {"tag": None, "fournisseur": None},
    "besoin accompagnement": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "bourse échelon": {"tag": "Statut boursier", "fournisseur": "CNOUS"},
    "bourse": {"tag": "Statut boursier", "fournisseur": "CNOUS"},
    "boursier": {"tag": "Statut boursier", "fournisseur": "CNOUS"},
    "Carte invalidité": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "Carte Mobilité Inclusion": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "carte mobilité inclusion": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "carte SNCF": {"tag": None, "fournisseur": None},
    "carte transport": {"tag": None, "fournisseur": None},
    "cécité": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "certificat médical": {"tag": None, "fournisseur": None},
    "chômeur": {"tag": "Demandeur d'emploi", "fournisseur": "FRANCE TRAVAIL"},
    "collège": {"tag": "Statut élève", "fournisseur": None},
    "collégien": {"tag": "Statut élève", "fournisseur": None},
    "Complémentaire Santé Solidaire": {"tag": None, "fournisseur": None},
    "condition ressource": {"tag": None, "fournisseur": None},
    "Contrat Adaptation": {"tag": None, "fournisseur": None},
    "contrat aidé": {"tag": None, "fournisseur": None},
    "contrat Engagement Jeune": {"tag": None, "fournisseur": None},
    "contrat Unique Insertion": {"tag": None, "fournisseur": None},
    "Corps Européen Solidarité": {"tag": None, "fournisseur": None},
    "couple": {"tag": None, "fournisseur": None},
    "crédit impôt": {"tag": None, "fournisseur": None},
    "déficient visuel auditif": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "demandeur d'asile": {"tag": None, "fournisseur": None},
    "demandeur d'emploi": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "demandeur d'emploi indemnisé": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "demandeur d'emploi longue durée": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "demandeur d'emploi non indemnisé": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "Demi-pensionnaire Externe": {"tag": "Statut élève", "fournisseur": "MEN"},
    "demi-pensionnaire": {"tag": "Statut élève", "fournisseur": "MEN"},
    "domicilié": {"tag": None, "fournisseur": None},
    "école Deuxième chance": {"tag": "Statut élève", "fournisseur": "MEN"},
    "élève interne": {"tag": "Statut élève", "fournisseur": "MEN"},
    "élève maternelle": {"tag": "Statut élève", "fournisseur": "MEN"},
    "élève primaire": {"tag": "Statut élève", "fournisseur": "MEN"},
    "élève secondaire": {"tag": "Statut élève", "fournisseur": "MEN"},
    "enfant supplémentaire": {"tag": None, "fournisseur": None},
    "étudiant": {"tag": "Statut étudiant", "fournisseur": "CNOUS"},
    "euro": {"tag": None, "fournisseur": None},
    "exonération": {"tag": None, "fournisseur": None},
    "exonéré impôt": {"tag": None, "fournisseur": None},
    "famille nombreuse": {"tag": None, "fournisseur": None},
    "fauteuil roulant": {"tag": None, "fournisseur": None},
    "formation professionnelle": {"tag": None, "fournisseur": None},
    "foyer fiscal": {"tag": None, "fournisseur": None},
    "foyer": {"tag": None, "fournisseur": None},
    "France Travail": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "guerre": {"tag": None, "fournisseur": None},
    "handicap": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "imposable": {"tag": None, "fournisseur": None},
    "inapte": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "incapacité permanente": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "indemnisé": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "indemnité journalière": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "indemnité": {"tag": None, "fournisseur": None},
    "insertion": {"tag": None, "fournisseur": None},
    "interne enfant": {"tag": None, "fournisseur": None},
    "invalide civil": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "invalide travail": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "invalide": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "invalidité temporaire": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "invalidité": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "jeune": {"tag": "Age", "fournisseur": None},
    "junior": {"tag": "Age", "fournisseur": None},
    "lycéen boursier": {"tag": "Statut boursier", "fournisseur": "MEN"},
    "lycéen": {"tag": "Statut élève", "fournisseur": "MEN"},
    "mal voyant": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "mention cécité": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "militaire": {"tag": "Statut militaire", "fournisseur": "MINARM"},
    "minima social": {"tag": "RSA", "fournisseur": "CNAF / MSA"},
    "minimum vieillesse": {"tag": None, "fournisseur": "CNAV"},
    "Mission Locale": {"tag": None, "fournisseur": None},
    "mobilisé action insertion": {"tag": None, "fournisseur": None},
    "mutilé": {"tag": None, "fournisseur": None},
    "non imposable": {"tag": None, "fournisseur": None},
    "non imposition": {"tag": None, "fournisseur": None},
    "non rémunéré": {"tag": None, "fournisseur": None},
    "non voyant": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "non-éligible": {"tag": None, "fournisseur": None},
    "non-imposable": {"tag": None, "fournisseur": None},
    "participation financière": {"tag": None, "fournisseur": None},
    "pension invalidité": {"tag": None, "fournisseur": None},
    "Plafond ressource": {"tag": None, "fournisseur": None},
    "pôle emploi": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "présentation attestation": {"tag": None, "fournisseur": None},
    "Prestation Compensation Handicap": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "Prime Activité": {"tag": None, "fournisseur": "CNAF / MSA"},
    "Programme Compétence": {"tag": None, "fournisseur": None},
    "protection temporaire": {"tag": None, "fournisseur": None},
    "quotient familial": {
        "tag": "Quotient Familial",
        "fournisseur": "CNAF / MSA",
    },
    "recherche emploi": {
        "tag": "Demandeur d'emploi",
        "fournisseur": "FRANCE TRAVAIL",
    },
    "réduction": {"tag": None, "fournisseur": None},
    "réfugié": {"tag": None, "fournisseur": None},
    "régularisation administrative": {"tag": None, "fournisseur": None},
    "rémunération mensuelle": {"tag": None, "fournisseur": None},
    "rémunéré": {"tag": None, "fournisseur": None},
    "résident principal": {"tag": None, "fournisseur": None},
    "ressortissant ukrainien": {"tag": None, "fournisseur": None},
    "ressource": {"tag": None, "fournisseur": None},
    "retraite": {"tag": "Retraité", "fournisseur": "CNAV"},
    "retraité": {"tag": "Retraité", "fournisseur": "CNAV"},
    "retrouvé emploi": {"tag": None, "fournisseur": None},
    "revenu foyer": {"tag": None, "fournisseur": None},
    "revenu imposable": {"tag": None, "fournisseur": None},
    "revenu mensuel": {"tag": None, "fournisseur": None},
    "RSA majoré": {"tag": "RSA", "fournisseur": "CNAF / MSA"},
    "RSA socle": {"tag": "RSA", "fournisseur": "CNAF / MSA"},
    "rupture familiale": {"tag": None, "fournisseur": None},
    "salarié": {"tag": None, "fournisseur": None},
    "sans sur mention": {"tag": None, "fournisseur": None},
    "scolaire": {"tag": "Statut élève", "fournisseur": "MEN"},
    "scolarisé": {"tag": "Statut élève", "fournisseur": "MEN"},
    "sénior": {"tag": "Age", "fournisseur": None},
    "service civique": {"tag": None, "fournisseur": None},
    "stagiaire": {"tag": "Statut étudiant", "fournisseur": "CNOUS"},
    "solidaire": {"tag": "Quotient Familial", "fournisseur": "CNAF / MSA"},
    "statut debout pénible": {
        "tag": "Statut handicapé",
        "fournisseur": "CNSA",
    },
    "sur mention": {"tag": None, "fournisseur": None},
    "sur-mention": {"tag": None, "fournisseur": None},
    "tarif": {"tag": None, "fournisseur": None},
    "taux handicap": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "titulaire Contrat": {"tag": None, "fournisseur": None},
    "tout public": {"tag": None, "fournisseur": None},
    "travailleur professionnel": {"tag": None, "fournisseur": None},
    "veuve": {"tag": None, "fournisseur": None},
    "vivre seul": {"tag": None, "fournisseur": None},
    # Acronymes
    "BA": {"tag": None, "fournisseur": None},
    "AAH": {"tag": "Statut handicapé", "fournisseur": "CNSA"},
    "ACCES": {"tag": None, "fournisseur": None},
    "ACTP": {"tag": None, "fournisseur": None},
    "ADA": {"tag": None, "fournisseur": None},
    "AEEH": {"tag": None, "fournisseur": None},
    "AFPA": {"tag": None, "fournisseur": None},
    "AME": {"tag": None, "fournisseur": None},
    "ARE": {"tag": None, "fournisseur": None},
    "AS": {"tag": None, "fournisseur": None},
    "ASA": {"tag": None, "fournisseur": None},
    "ASP": {"tag": None, "fournisseur": None},
    "ASPA": {"tag": None, "fournisseur": None},
    "ASS": {"tag": None, "fournisseur": None},
    "C.A.E": {"tag": None, "fournisseur": None},
    "C.A.V": {"tag": None, "fournisseur": None},
    "CAE": {"tag": None, "fournisseur": None},
    "CAF": {"tag": None, "fournisseur": None},
    "CASAR": {"tag": None, "fournisseur": None},
    "CAV": {"tag": None, "fournisseur": None},
    "CCAS": {"tag": None, "fournisseur": None},
    "CDAPH": {"tag": None, "fournisseur": None},
    "CDDU": {"tag": None, "fournisseur": None},
    "CEJ": {"tag": None, "fournisseur": None},
    "CFA": {"tag": None, "fournisseur": None},
    "CIE": {"tag": None, "fournisseur": None},
    "CM2": {"tag": None, "fournisseur": None},
    "CMI": {"tag": None, "fournisseur": None},
    "CMU": {"tag": None, "fournisseur": None},
    "CMU-C": {"tag": None, "fournisseur": None},
    "CMUC": {"tag": None, "fournisseur": None},
    "CNASEA": {"tag": None, "fournisseur": None},
    "CROUS": {"tag": None, "fournisseur": None},
    "CSS": {"tag": None, "fournisseur": None},
    "CUI": {"tag": None, "fournisseur": None},
    "ESAT": {"tag": None, "fournisseur": None},
    "MDPH": {"tag": None, "fournisseur": None},
    "MSA": {"tag": None, "fournisseur": None},
    "ONAC": {"tag": None, "fournisseur": None},
    "PACEA": {"tag": None, "fournisseur": None},
    "PCH": {
        "tag": "Prestation de compensation du handicap",
        "fournisseur": "CNSA",
    },
    "PDA": {"tag": None, "fournisseur": None},
    "PDE": {"tag": None, "fournisseur": None},
    "PDIE": {"tag": None, "fournisseur": None},
    "PEC": {"tag": None, "fournisseur": None},
    "PMR": {"tag": None, "fournisseur": None},
    "QF": {"tag": "Quotient Familial", "fournisseur": "CNAF / MSA"},
    "RFR": {"tag": None, "fournisseur": None},
    "RSA": {"tag": "RSA", "fournisseur": "CNAF / MSA"},
    "SEGPA": {"tag": None, "fournisseur": None},
    "SMIC": {"tag": None, "fournisseur": None},
}


BLACK_LIST = [
    "canebière bourse",
    "bourse du travail",
    "place de la bourse",
    "actif",
]
