# Tokens et expressions critères d'éligibilité (seront traités par SpaCy)
TOKENS_ELIGIBILITE = [
    "€",
    "barre bleue",
    "barre rouge",
    "barres bleues",
    "barres rouges",
    "mobilisé action insertion",
    "accompagnant PMR",
    "accompagnateur",
    "actif",
    "adulte salarié",
    "allocataire",
    "Allocation Adulte Handicapé",
    "allocation RSA activité",
    "Allocation Compensatrice Tierce Personne",
    "Allocation Solidarité Spécifique",
    "Allocation Soutien Familial",
    "Allocation Personnalisée Autonomie",
    "allocation vieillesse",
    "allocations journalières",
    "ancien combattant",
    "apprenti",
    "asile",
    "autonome marche",
    "crédit impôt",
    "sur mention",
    "sur-mention",
    "avenir Jeunes",
    "aveugle",
    "ayant-droit",
    "baccalauréat",
    "bénéficiaire",
    "besoin accompagnement",
    "bourse",
    "bourse échelon",
    "boursier",
    "Carte invalidité",
    "carte transport",
    "Carte Mobilité Inclusion",
    "carte mobilité inclusion",
    "carte SNCF",
    "cécité",
    "certificat médical",
    "chômeur",
    "collège",
    "collégien",
    "combattant",
    "Complémentaire Santé Solidaire",
    "condition ressource",
    "contrat aidé",
    "Contrat Adaptation",
    "contrat Engagement Jeune",
    "contrat Unique Insertion",
    "Corps Européen Solidarité",
    "couple",
    "déficient visuel auditif",
    "demandeur emploi",
    "demandeur emploi indemnisé",
    "demandeur emploi longue durée",
    "demandeur emploi non indemnisé",
    "demi-pensionnaire",
    "Demi-pensionnaire Externe",
    "échelon",
    "école Deuxième chance",
    "élève maternelle",
    "élève primaire",
    "élève secondaire",
    "élève interne",
    "régularisation administrative",
    "autonome fiscalement",
    "demandeur asile",
    "domicilié",
    "résident principal",
    "titulaire Contrat",
    "étudiant",
    "euro",
    "exonération",
    "exonéré impôt",
    "famille nombreuse",
    "fauteuil roulant",
    "formation professionnelle",
    "foyer",
    "foyer fiscal",
    "France Travail",
    "guerre",
    "handicap",
    "imposable",
    "inapte",
    "incapacité permanente",
    "indemnisé",
    "indemnité",
    "indemnité journalière",
    "insertion",
    "interne enfant",
    "invalide civil",
    "invalide travail",
    "invalide",
    "invalidité",
    "invalidité temporaire",
    "jeune",
    "junior",
    "lycéen",
    "lycéen boursier",
    "mal voyant",
    "mention cécité",
    "militaire",
    "minima social",
    "minimum vieillesse",
    "Mission Locale",
    "mutilé",
    "non imposable",
    "non imposition",
    "non rémunéré",
    "non voyant",
    "non-éligible",
    "non-imposable",
    "enfant supplémentaire",
    "participation financière",
    "pension invalidité",
    "Plafond ressource",
    "pôle emploi",
    "présentation attestation",
    "Prestation Compensation Handicap",
    "Prime Activité",
    "Programme Compétence",
    "protection temporaire",
    "quotient familial",
    "recherche emploi",
    "réfugié",
    "rémunération mensuelle",
    "rémunéré",
    "ressortissant ukrainien",
    "ressource",
    "retraite",
    "retraité",
    "retrouvé emploi",
    "revenu mensuel",
    "revenu foyer",
    "revenu imposable",
    "RSA majoré",
    "RSA socle",
    "rupture familiale",
    "salarié",
    "sans sur mention",
    "scolaire",
    "scolarisé",
    "sénior",
    "service civique",
    "solidaire",
    "stagiaire",
    "statut debout pénible",
    "tarif",
    "taux handicap",
    "terminale",
    "tout public",
    "travailleur professionnel",
    "veuve",
    "vivre seul",
    "réduction",
    "bourse échelon",
    "échelon CROUS",
]
